# This script serves to finalize the source code before compilation process.
# If you only mean to compile the project from source and use it, you don't have to use this
# this needs to be run whenever something is changed in productions.txt to reflect those 
# changes onto the cpp codebase.
from pathlib import Path

def define_ast(outputDir: str, baseName: str, types: list):
    script_dir = Path(__file__).resolve().parent
    file_path = (script_dir / outputDir / f"ast_classes.h").resolve()
    with open(file_path, "w", encoding="utf-8") as file:
        file.write("//Contents of this file are autogenerated by scripts/gen_ast_classes.py\n")
        file.write("class "+baseName+"{\n")

        file.write("}\n")
type_list = []
with open("classes_data.txt", "r", encoding="utf-8") as file:
    content = file.read()
    type_list = content.split("\n")

    
define_ast("../include", "Expression", [])