# This script serves to finalize the source code before compilation process.
# If you only mean to compile the project from source and use it, you don't have to use this
# this needs to be run whenever something is changed in classes_data.txt to reflect those 
# changes onto the cpp codebase.
from pathlib import Path

def define_ast(outputDir: str, baseName: str, types: list):
    script_dir = Path(__file__).resolve().parent
    file_path = (script_dir / outputDir / f"ast_utils.h").resolve()
    with open(file_path, "w", encoding="utf-8") as file:
        file.write("//Contents of this file are autogenerated by scripts/gen_ast_classes.py\n")
        for type in types:
            file.write("class "+ type[0] + baseName + ": public "+ baseName +"{\n")
            temp = type[0]
            type.pop(0)
            print(type)
            
            file.write("    public:\n")
            for i in range(int(len(type)/2)):
                file.write("        "+type[2*i]+" "+type[2*i+1]+";\n")
            file.write("        "+temp+baseName+"(")
            for i in range(int(len(type)/2)):
                file.write(type[2*i]+" "+type[2*i+1])
                if i < int(len(type)/2)-1:
                    file.write(", ")
            file.write(") : ")
            for i in range(int(len(type)/2)):
                needs_move = False
                if "unique_ptr" in type[2*i]:
                    needs_move = True
                if not needs_move:
                    file.write(type[2*i+1]+"("+type[2*i+1]+")")
                else:
                    file.write(type[2*i+1]+"(std::move("+type[2*i+1]+"))")
                if i < int(len(type)/2)-1:
                    file.write(", ")
                else:
                    file.write('{}\n')
            file.write("};\n")
type_list = []
with open("classes_data.txt", "r", encoding="utf-8") as file:
    content = file.read()
    type_list = content.split("\n")
for i in range(len(type_list)):
    type_list[i] = type_list[i].split(" ")


    
define_ast("../include", "Expr", type_list)