//Contents of this file are autogenerated by scripts/gen_ast_classes.py
class LiteralExpr: public Expr{
    public:
        Literal value;
        LiteralExpr(Literal value) : value(value){}
};
class VariableExpr: public Expr{
    public:
        std::string name;
        VariableExpr(std::string name) : name(name){}
};
class BinaryExpr: public Expr{
    public:
        std::unique_ptr<Expr> left;
        Token operator;
        std::unique_ptr<Expr> right;
        BinaryExpr(std::unique_ptr<Expr> left, Token operator, std::unique_ptr<Expr> right) : left(std::move(left)), operator(operator), right(std::move(right)){}
};
